apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-pvc
  namespace: user-fave
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-sc
